### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [hanamiyuna/hapin-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by hanamiyuna** [comment]
Very proud to hear this.
Thank you very much for looking at this repo!
I have updated it and along with many detail inside README.md.

Look forward to see more goods in awesome-zsh-plugins

**Comment by unixorn** [comment]
Thanks! Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/854
